version: "3"

services:
    elgg:
        build: ./image_www
        image: seedlab-img-www
        container_name: elgg-10.9.0.51
        tty: true
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.51

    mysql:
        build: ./image_mysql
        image: seedlab-img-mysql
        container_name: mysql-10.9.0.61
        command: --default-authentication-plugin=mysql_native_password
        tty: true
        restart: always
        cap_add:
                - SYS_NICE  
        volumes:
                - ./mysql_data:/var/lib/mysql
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.61

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

